services:
    fedmdrs:
        build: .
        image: fedmdrs
        container_name: fedmdrs
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: cdi
                          capabilities: ["gpu"]
                          device_ids:
                              - nvidia.com/gpu=all
        volumes:
            - .:/workspace
