[project]
name = "FedMDRS"
version = "0.1.0"
dependencies = [
  "numpy",
  "networkx",
  "matplotlib",
  "scikit-learn",
  "optuna",
  "pate",
  "torch==1.13.1",
  "tqdm"
]

[tool.setuptools]
py-modules = []
