[project]
name = "FedMDRS"
version = "0.0.1"
description = "A small example package"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "networkx"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["FedMDRS"]
