[project]
name = "USAD"
version = "0.0.1"
description = "USAD"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "torch",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["FedMDRS"]
